version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: argocd-task
    AWS_DEFAULT_REGION: us-west-1

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=621533607727
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - docker build -t argocd-task:$IMAGE_TAG .
      - docker tag argocd-task:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd-task:$IMAGE_TAG

  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/argocd-task:$IMAGE_TAG